//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUKRaine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translate
    {
        public int TID { get; set; }
        public int WID { get; set; }
        public string Translate1 { get; set; }
        public string ImageLink { get; set; }
    }
}
