//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUKRaine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int UsID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string Donut { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<bool> Check_FirstTest { get; set; }
    }
}
